// eslint.config.mjs
//
// T11 cutover: `eslint-config-next` (and the React/`@next/next` plugins
// it pulled in) is gone along with Next.js itself. This project has no
// framework left to lint against — plain `@eslint/js` recommended rules
// plus `typescript-eslint`'s (non type-aware, syntax-only) recommended
// rules are enough: real type errors are already caught separately by
// `pnpm typecheck` (scripts/typecheck.mjs -> `tsc --noEmit`), so lint
// doesn't need a type-checked project service to be useful.
import { defineConfig, globalIgnores } from "eslint/config";
import js from "@eslint/js";
import tseslint from "typescript-eslint";

export default defineConfig([
  js.configs.recommended,
  ...tseslint.configs.recommended,
  globalIgnores([
    "dist/**",
    "dist-static/**",
    ".wrangler/**",
    ".next/**",
    "playwright-report/**",
    "test-results/**",
    // Wrangler-generated runtime types (regenerated by `pnpm run
    // types:worker`, not hand-maintained) — already carries its own
    // `/* eslint-disable */` for that reason.
    "worker-configuration.d.ts",
  ]),
  {
    rules: {
      // `no-undef` can't know about the ambient Node/Bun/DOM/Workers
      // globals every file here legitimately uses (process, URL,
      // Request/Response, console, fetch, ...) without a separate
      // `globals` dependency providing per-environment global lists —
      // and for `.ts`/`.tsx` files it's already redundant with `tsc`,
      // which resolves every one of those from `@types/node`/
      // `@types/bun`/lib.dom/worker-configuration.d.ts and fails the
      // build on a real undefined reference. See typescript-eslint's own
      // FAQ ("no-undef ... already handled by TypeScript").
      "no-undef": "off",
      // This project's existing convention (src/html/jsx-dev-runtime.ts's
      // discarded dev-only JSX params, src/html/jsx-runtime.ts's
      // discarded `key`) for "must be in this position but intentionally
      // unused" is a leading underscore, predating this lint config.
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },
]);
