// scripts/generate-contours.ts
//
// landing-craft T4: regenerates `public/piura-contours.svg` — real
// contour lines of the Piura highlands (Paimas / Ayabaca, the artisanal
// gold belt) from AWS Terrain Tiles (Terrarium PNG, SRTM-derived).
//
// Run manually: `bun run scripts/generate-contours.ts`. The output is
// committed; the site build never fetches anything.

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  type ContourLayer,
  contourLevels,
  contoursToSvg,
  joinSegments,
  marchingSquares,
  parsePng,
  simplify,
  terrariumElevation,
} from "../src/build/contours";

const ZOOM = 11;
const X_TILES = [568, 569, 570];
const Y_TILES = [1050, 1051];
const TILE = 256;
const DOWNSAMPLE = 2; // average 2x2 px → one sample (~150 m at this zoom)
const INTERVAL = 200; // meters
const INDEX_EVERY = 5; // every 1000 m is an index contour
const MIN_POINTS = 12; // drop tiny noise rings
const TOLERANCE = 0.5; // RDP tolerance in grid units
const OUT = join(import.meta.dir, "..", "public", "piura-contours.svg");

const tileUrl = (x: number, y: number) =>
  `https://s3.amazonaws.com/elevation-tiles-prod/terrarium/${ZOOM}/${x}/${y}.png`;

const fullW = X_TILES.length * TILE;
const fullH = Y_TILES.length * TILE;
const full = new Float32Array(fullW * fullH);

for (const [row, y] of Y_TILES.entries()) {
  for (const [col, x] of X_TILES.entries()) {
    const res = await fetch(tileUrl(x, y));
    if (!res.ok) throw new Error(`tile ${x}/${y}: HTTP ${res.status}`);
    const png = parsePng(new Uint8Array(await res.arrayBuffer()));
    for (let py = 0; py < TILE; py++) {
      for (let px = 0; px < TILE; px++) {
        const i = (py * TILE + px) * 3;
        full[(row * TILE + py) * fullW + col * TILE + px] = terrariumElevation(
          png.pixels[i],
          png.pixels[i + 1],
          png.pixels[i + 2],
        );
      }
    }
  }
}

const w = fullW / DOWNSAMPLE;
const h = fullH / DOWNSAMPLE;
const grid = new Float32Array(w * h);
for (let y = 0; y < h; y++) {
  for (let x = 0; x < w; x++) {
    let sum = 0;
    for (let dy = 0; dy < DOWNSAMPLE; dy++) {
      for (let dx = 0; dx < DOWNSAMPLE; dx++) {
        sum += full[(y * DOWNSAMPLE + dy) * fullW + x * DOWNSAMPLE + dx];
      }
    }
    grid[y * w + x] = sum / DOWNSAMPLE ** 2;
  }
}

let min = Infinity;
let max = -Infinity;
for (const v of grid) {
  if (v < min) min = v;
  if (v > max) max = v;
}

const layers: ContourLayer[] = contourLevels(min, max, INTERVAL).map((level) => ({
  level,
  index: level % (INTERVAL * INDEX_EVERY) === 0,
  lines: joinSegments(marchingSquares(grid, w, h, level))
    .filter((line) => line.length >= MIN_POINTS)
    .map((line) => simplify(line, TOLERANCE)),
}));

const svg = contoursToSvg({
  width: w,
  height: h,
  layers,
  comment: `Piura highlands, z${ZOOM} tiles x${X_TILES[0]}-${X_TILES.at(-1)} y${Y_TILES[0]}-${Y_TILES.at(-1)}, ${INTERVAL} m interval, ${Math.round(min)}-${Math.round(max)} m. Source: AWS Terrain Tiles (Terrarium, SRTM-derived). Generated by scripts/generate-contours.ts`,
});
writeFileSync(OUT, svg);
console.log(
  `wrote ${OUT}: ${(svg.length / 1024).toFixed(1)} KB, ${layers.length} levels, ${Math.round(min)}-${Math.round(max)} m`,
);
