#!/usr/bin/env node
// scripts/typecheck.mjs
//
// T11: no more `vinext typegen` step — that generated Next's typed-route
// declarations (`.next/types/routes.d.ts`), which no longer exist once
// Next.js is gone. `worker-configuration.d.ts` (Wrangler's own runtime
// type declaration, regenerated by `pnpm run types:worker` whenever
// wrangler.jsonc changes) is still a required, hand-checked-in file, so
// the sanity check below stays.
import { spawnSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "..");
const PNPM = process.platform === "win32" ? "pnpm.cmd" : "pnpm";
const workerTypesPath = resolve(ROOT, "worker-configuration.d.ts");

if (!existsSync(workerTypesPath)) {
  console.error(
    "worker-configuration.d.ts is missing. Run `pnpm run types:worker`.",
  );
  process.exit(1);
}

const workerTypes = readFileSync(workerTypesPath, "utf8");
if (!workerTypes.includes("Runtime types generated with workerd@")) {
  console.error(
    "worker-configuration.d.ts is not a Wrangler-generated runtime declaration.",
  );
  process.exit(1);
}

const result = spawnSync(PNPM, ["exec", "tsc", "--noEmit"], {
  cwd: ROOT,
  stdio: "inherit",
});
if (result.error) {
  console.error(result.error.message);
  process.exit(1);
}
process.exit(result.status ?? 1);
