#!/usr/bin/env node
/**
 * Pre-build / pre-commit environment validator.
 *
 * Checks that the project is ready to build, test, and (eventually) deploy.
 * No external dependencies — runs with plain `node`.
 *
 * Usage:  node scripts/validate-env.mjs
 * Exit:   0 on success, 1 on any failure.
 */
import { existsSync, readFileSync, statSync } from "node:fs";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(fileURLToPath(new URL("..", import.meta.url)));
const fail = [];
const warn = [];

/** Safe JSON.parse: returns null on error, records a failure with `name`. */
function readJson(name, filePath) {
  let raw;
  try {
    raw = readFileSync(filePath, "utf8");
  } catch (err) {
    fail.push(`${name} (cannot read: ${err.message})`);
    return null;
  }
  try {
    return JSON.parse(raw);
  } catch (err) {
    fail.push(`${name} (invalid JSON: ${err.message})`);
    return null;
  }
}

/** Record a check. Status is "ok" if `cond` is truthy. */
function check(name, cond, msg) {
  if (cond) {
    process.stdout.write(`  \u2713 ${name}\n`);
  } else {
    process.stdout.write(`  \u2717 ${name} \u2014 ${msg}\n`);
    fail.push(name);
  }
}

function note(name, cond, msg) {
  if (!cond) {
    process.stdout.write(`  ! ${name} \u2014 ${msg}\n`);
    warn.push(name);
  }
}

process.stdout.write("\n== Environment validation ==\n\n");

// 1. Node + pnpm version. `engines.node` is the single source of truth;
// versions are compared numerically (as strings, "22.9.0" >= "22.13.0").
const pkg = readJson("package.json", join(ROOT, "package.json")) ?? {};
const minNode = pkg.engines?.node?.replace(/^>=/, "") ?? "0.0.0";
function atLeast(version, minimum) {
  const [a, b] = [version, minimum].map((v) => v.split(".").map(Number));
  const i = a.findIndex((n, idx) => n !== b[idx]);
  return i === -1 || a[i] > b[i];
}
const nodeOk = atLeast(process.versions.node, minNode);
check(`Node >= ${minNode}`, nodeOk, `found ${process.versions.node}`);
const expectedPnpm = pkg.packageManager?.replace("pnpm@", "").split("+", 1)[0];
const actualPnpm = process.env.npm_config_user_agent?.match(/pnpm\/(\S+)/)?.[1];
note(
  `pnpm ${expectedPnpm} (package.json pins this)`,
  actualPnpm === expectedPnpm,
  actualPnpm
    ? `found ${actualPnpm} (mismatch with package.json)`
    : `could not detect pnpm version (run via \`pnpm run validate\`, not \`node\`, to verify)`,
);

// 2. Lockfile is in sync with package.json
const lockExists = existsSync(join(ROOT, "pnpm-lock.yaml"));
check("pnpm-lock.yaml present", lockExists, "run `pnpm install` first");

// 3. Required files — the static build's own footprint (T11 cutover):
// no more app/layout.tsx, app/page.tsx, or Next's generator routes
// (robots.ts/sitemap.ts/manifest.ts) — those are now src/build/*.ts,
// pure functions wired into build.ts and checked by bun test. Only
// app/constants.ts, app/globals.css, and the 2 API route handlers
// survive from the old app/ tree (see build.ts's CSS_ENTRY and
// src/worker/index.ts's imports for why).
const required = [
  "app/constants.ts",
  "app/globals.css",
  "app/api/crm-lead/route.ts",
  "app/api/next-business-day/route.ts",
  "src/build/build.ts",
  "src/worker/index.ts",
  "wrangler.jsonc",
  "public/og.jpg",
  "public/favicon.ico",
  "public/apple-touch-icon.png",
  "scripts/validate-env.mjs",
  ".env.example",
];
for (const f of required) {
  check(`file present: ${f}`, existsSync(join(ROOT, f)), "missing");
}

// 4. Public assets within size budgets
// P6: WhatsApp link previews are unreliable for heavy images.
const ogSize = existsSync(join(ROOT, "public/og.jpg"))
  ? statSync(join(ROOT, "public/og.jpg")).size
  : Infinity;
check(
  "public/og.jpg <= 200 KB",
  ogSize <= 200 * 1024,
  `${(ogSize / 1024).toFixed(0)} KB`,
);

// 5. Security headers now come from a single source: src/build/security-policy.ts
// (T10/T11). It feeds both dist-static/_headers (generated at build time
// by src/build/headers.ts, applied by Cloudflare to every static-asset
// response) and src/worker/security-headers.ts (wraps the 2 API
// responses, since Cloudflare never applies _headers to a response the
// Worker script itself returns). public/_headers — the old SSR-era file
// that documented Cloudflare never even applying it — was deleted at the
// T11 cutover; its reappearance would mean two, possibly conflicting,
// sources of truth for the same headers.
check(
  "public/_headers was removed (dist-static/_headers, generated by src/build/headers.ts, is the single source of truth)",
  !existsSync(join(ROOT, "public/_headers")),
  "public/_headers reappeared — remove it or update src/build/headers.ts accordingly",
);

const securityPolicyRaw = existsSync(join(ROOT, "src/build/security-policy.ts"))
  ? readFileSync(join(ROOT, "src/build/security-policy.ts"), "utf8")
  : "";
check(
  "src/build/security-policy.ts declares CSP",
  /CSP_DIRECTIVES/.test(securityPolicyRaw) && /script-src/.test(securityPolicyRaw),
  "CSP directives missing from src/build/security-policy.ts",
);
check(
  "src/build/security-policy.ts declares HSTS",
  /Strict-Transport-Security/i.test(securityPolicyRaw),
  "HSTS header missing from src/build/security-policy.ts",
);
check(
  "src/build/security-policy.ts's script-src has no 'unsafe-inline'/'unsafe-eval'",
  !/script-src[^\n]*'unsafe-(inline|eval)'/.test(securityPolicyRaw),
  "found 'unsafe-inline'/'unsafe-eval' in script-src",
);

// 6. .env files: warn if a real one is committed (should only have .example)
const envFiles = [".env", ".env.local", ".env.production"];
for (const f of envFiles) {
  const p = join(ROOT, f);
  note(
    `${f} not present (only .env.example should exist in repo)`,
    !existsSync(p),
    `found real env file — verify it has no secrets before committing`,
  );
}

// 7. node_modules installed
check(
  "node_modules present",
  existsSync(join(ROOT, "node_modules")),
  "run `pnpm install` first",
);

// 8. cominorsa-web is a static site + one Worker (dist-static/ Static
// Assets + src/worker/index.ts's /api/* handlers), with no persistent
// storage (form is WhatsApp-based, no DB). wrangler.jsonc must declare
// no d1_databases/r2_buckets bindings — those existed as vinext/Vite
// placeholders pre-cutover (.openai/hosting.json, removed at T11) and
// were never actually consumed by any handler.
const wranglerRaw = existsSync(join(ROOT, "wrangler.jsonc"))
  ? readFileSync(join(ROOT, "wrangler.jsonc"), "utf8")
  : "";
check(
  "wrangler.jsonc declares no d1_databases binding",
  !/"d1_databases"/.test(wranglerRaw),
  "project does not use D1 — remove d1_databases from wrangler.jsonc",
);
check(
  "wrangler.jsonc declares no r2_buckets binding",
  !/"r2_buckets"/.test(wranglerRaw),
  "project does not use R2 — remove r2_buckets from wrangler.jsonc",
);

process.stdout.write("\n== Summary ==\n\n");
if (fail.length === 0) {
  process.stdout.write(
    `\u2713 all required checks passed (${warn.length} warnings)\n`,
  );
  if (warn.length > 0) {
    process.stdout.write(`  warnings: ${warn.join(", ")}\n`);
  }
  process.exit(0);
} else {
  process.stdout.write(
    `\u2717 ${fail.length} check(s) failed: ${fail.join(", ")}\n`,
  );
  process.exit(1);
}
